/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminMateriaisRouteImport } from './routes/admin.materiais'
import { Route as AdminMentoriasRouteImport } from './routes/admin.mentorias'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunoAgendaRouteImport } from './routes/aluno.agenda'
import { Route as AlunoCallRouteImport } from './routes/aluno.call'
import { Route as AlunoCursosRouteImport } from './routes/aluno.cursos'
import { Route as AlunoMateriaisRouteImport } from './routes/aluno.materiais'
import { Route as AlunoPagamentosRouteImport } from './routes/aluno.pagamentos'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AlunoCursosCourseIdRouteImport } from './routes/aluno.cursos.$courseId'
import { Route as ApiPublicKiwifyRouteImport } from './routes/api/public/kiwify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriaisRoute = AdminMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentoriasRoute = AdminMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCallRoute = AlunoCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCursosRoute = AlunoCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoMateriaisRoute = AlunoMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoPagamentosRoute = AlunoPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AlunoRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AlunoCursosCourseIdRoute = AlunoCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AlunoCursosRoute,
} as any)
const ApiPublicKiwifyRoute = ApiPublicKiwifyRouteImport.update({
  id: '/api/public/kiwify',
  path: '/api/public/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/call': typeof AlunoCallRoute
  '/aluno/cursos': typeof AlunoCursosRouteWithChildren
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/pagamentos': typeof AlunoPagamentosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/cursos/$courseId': typeof AlunoCursosCourseIdRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/call': typeof AlunoCallRoute
  '/aluno/cursos': typeof AlunoCursosRouteWithChildren
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/pagamentos': typeof AlunoPagamentosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/aluno/cursos/$courseId': typeof AlunoCursosCourseIdRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/call': typeof AlunoCallRoute
  '/aluno/cursos': typeof AlunoCursosRouteWithChildren
  '/aluno/materiais': typeof AlunoMateriaisRoute
  '/aluno/pagamentos': typeof AlunoPagamentosRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/cursos/$courseId': typeof AlunoCursosCourseIdRoute
  '/api/public/kiwify': typeof ApiPublicKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/aluno/agenda'
    | '/aluno/call'
    | '/aluno/cursos'
    | '/aluno/materiais'
    | '/aluno/pagamentos'
    | '/auth/reset-password'
    | '/admin/'
    | '/aluno/'
    | '/aluno/cursos/$courseId'
    | '/api/public/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/aluno/agenda'
    | '/aluno/call'
    | '/aluno/cursos'
    | '/aluno/materiais'
    | '/aluno/pagamentos'
    | '/auth/reset-password'
    | '/admin'
    | '/aluno'
    | '/aluno/cursos/$courseId'
    | '/api/public/kiwify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/aluno/agenda'
    | '/aluno/call'
    | '/aluno/cursos'
    | '/aluno/materiais'
    | '/aluno/pagamentos'
    | '/auth/reset-password'
    | '/admin/'
    | '/aluno/'
    | '/aluno/cursos/$courseId'
    | '/api/public/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicKiwifyRoute: typeof ApiPublicKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materiais': {
      id: '/admin/materiais'
      path: '/materiais'
      fullPath: '/admin/materiais'
      preLoaderRoute: typeof AdminMateriaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentorias': {
      id: '/admin/mentorias'
      path: '/mentorias'
      fullPath: '/admin/mentorias'
      preLoaderRoute: typeof AdminMentoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/agenda': {
      id: '/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/call': {
      id: '/aluno/call'
      path: '/call'
      fullPath: '/aluno/call'
      preLoaderRoute: typeof AlunoCallRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/cursos': {
      id: '/aluno/cursos'
      path: '/cursos'
      fullPath: '/aluno/cursos'
      preLoaderRoute: typeof AlunoCursosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/materiais': {
      id: '/aluno/materiais'
      path: '/materiais'
      fullPath: '/aluno/materiais'
      preLoaderRoute: typeof AlunoMateriaisRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/pagamentos': {
      id: '/aluno/pagamentos'
      path: '/pagamentos'
      fullPath: '/aluno/pagamentos'
      preLoaderRoute: typeof AlunoPagamentosRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/aluno/cursos/$courseId': {
      id: '/aluno/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/aluno/cursos/$courseId'
      preLoaderRoute: typeof AlunoCursosCourseIdRouteImport
      parentRoute: typeof AlunoCursosRoute
    }
    '/api/public/kiwify': {
      id: '/api/public/kiwify'
      path: '/api/public/kiwify'
      fullPath: '/api/public/kiwify'
      preLoaderRoute: typeof ApiPublicKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminMateriaisRoute: typeof AdminMateriaisRoute
  AdminMentoriasRoute: typeof AdminMentoriasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAlunosRoute: AdminAlunosRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminMateriaisRoute: AdminMateriaisRoute,
  AdminMentoriasRoute: AdminMentoriasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoCursosRouteChildren {
  AlunoCursosCourseIdRoute: typeof AlunoCursosCourseIdRoute
}

const AlunoCursosRouteChildren: AlunoCursosRouteChildren = {
  AlunoCursosCourseIdRoute: AlunoCursosCourseIdRoute,
}

const AlunoCursosRouteWithChildren = AlunoCursosRoute._addFileChildren(
  AlunoCursosRouteChildren,
)

interface AlunoRouteChildren {
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoCallRoute: typeof AlunoCallRoute
  AlunoCursosRoute: typeof AlunoCursosRouteWithChildren
  AlunoMateriaisRoute: typeof AlunoMateriaisRoute
  AlunoPagamentosRoute: typeof AlunoPagamentosRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoCallRoute: AlunoCallRoute,
  AlunoCursosRoute: AlunoCursosRouteWithChildren,
  AlunoMateriaisRoute: AlunoMateriaisRoute,
  AlunoPagamentosRoute: AlunoPagamentosRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicKiwifyRoute: ApiPublicKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
